apps/goods/urls.py
from django.urls import path, re_path

from apps.goods import views

urlpatterns = [
    path('sj_index/', views.sj_index, name='sj_index'),  # 商家首页
    path('find', views.MySearchView(), name='haystack'),  # 全站检索
    re_path(r'^wm_index/(?P<code>[0-4])/(?P<page>\d+)/$', views.WmIndexView.as_view(), name='wm_index'),  # 店铺列表
    re_path(r'^goods/(?P<goods_id>\d+)/(?P<a_page>\d+)/(?P<b_page>\d+)/(?P<c_page>\d+)$',
        views.ShopDetailView.as_view(), name='shop_detail'),  # 店铺详情页
    path('', views.index, name='index')  # 买家首页
]

apps/goodsmanage/urls.py
from django.conf.urls import re_path

from apps.goodsmanage.views import SjcpglView, SjcpglUpdateView

urlpatterns = [
    re_path(r'^sj_cpgl/(?P<page>\d+)/$', SjcpglView.as_view(), name='sj_cpgl'),  # 商品管理
    re_path(r'^sj_cpgl_update/(?P<goods_id>(\d+))/$', SjcpglUpdateView.as_view(), name='sj_cpgl_update'),  # 商品修改
    re_path(r'^update_del/(?P<sku_id>(\d+))/$', SjcpglUpdateView.update_del, name='update_del'),  # 商品删除
]

apps/order/urls.py
from django.urls import path

from apps.order.views import OrderGenerateView, OrderPayView, CheckPayView, OrderBuySuccessView, QueryOrderView, GoCommentView

urlpatterns = [
    path('generate/', OrderGenerateView.as_view(), name='generate'),
    path('pay/', OrderPayView.as_view(), name='pay'),
    path('check/', CheckPayView.as_view(), name='check'),
    path('success/<order_id>', OrderBuySuccessView.as_view(), name='success'),
    path('go_comment/<order_id>', GoCommentView.as_view(), name='go_comment'),
    path('query/<page>/', QueryOrderView.as_view(), name='query')
]

apps/user/urls.py
from django.urls import path, re_path
from . import views
from apps.user.views import RegisterView, LoginView, LogoutView, ShopRegisterView, UserActivate

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),  # 用户注册
    path('sj_register/', ShopRegisterView.as_view(), name='sj_register'),  # 店铺注册
    path('login/', LoginView.as_view(), name='login'),  # 用户登录
    path('logout/', LogoutView.as_view(), name='logout'),  # 用户登出
    re_path(r'^activate/(?P<token>.*)$', UserActivate.as_view(), name='activate'),  # 用户激活
    re_path(r'^type_detail$', views.find_type, name='type_detail'),  # 详细类型
]

clmwm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('apps.user.urls', 'apps.user'), namespace='user')),  # 用户模块
    path('cart/', include(('apps.cart.urls', 'apps.cart'), namespace='cart')),  # 购物车模块
    path('order/', include(('apps.order.urls', 'apps.order'), namespace='order')),  # 订单模块
    path('ordermanage/', include(('apps.ordermanage.urls', 'apps.ordermanage'), namespace='ordermanage')),  # 订单管理模块
    path('goodsmanage/', include(('apps.goodsmanage.urls', 'apps.goodsmanage'), namespace='goodsmanage')),  # 商品管理模块
    path('commentmanage/', include(('apps.commentmanage.urls', 'apps.commentmanage'), namespace='commentmanage')),  # 评论管理模块
    path('comment/', include(('apps.comment.urls', 'apps.comment'), namespace='comment')),  # 评论模块
    path('', include(('apps.goods.urls', 'apps.goods'), namespace='goods')),  # 商品模块,首页
]

# 仅在DEBUG模式下加载模块
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/index.html
{% extends 'mj.html' %}
{% load staticfiles %}
{% block title %}吃了么{% endblock title %}
{% block topfiles %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/Popt.js' %}"></script>
<script src="{% static 'js/cityJson.js' %}"></script>
<script src="{% static 'js/citySet.js' %}"></script>
{% endblock topfiles %}
{% block body %}
<div id="banner">
     <nav>
        <ul>
            <li><a href="{% url 'goods:wm_index' '0' '1'%}"><img src="{% static 'image/zc.png' %}">中餐</a></li>
            <li><a href="{% url 'goods:wm_index' '1' '1'%}"><img src="{% static 'image/xc.png' %}">西餐</a></li>
            <li><a href="{% url 'goods:wm_index' '2' '1'%}"><img src="{% static 'image/sg.png' %}">水果</a></li>
            <li><a href="{% url 'goods:wm_index' '3' '1'%}"><img src="{% static 'image/yp.png' %}">饮品</a></li>
        </ul>
     </nav>
     <div class="banner">
     </div>
</div>
{#<input id="input-id" type="number" class="rating" min=0 max=5 step=0.5 data-size="lg" >#}
<div id="dinner">
   <div class="dinner_title">
      <h2>中餐</h2><a href="{% url 'goods:wm_index' '0' '1'%}">查看全部></a>
   </div>
   <div class="dinner_con_bg">
      <div class="dinner_con">

          <ul>
            {% for item in shop_info0 %}
            <li>
            <a href="{% url 'goods:shop_detail' item.id '1'  '1' '1' %}">
               <img src="{{ item.shop_image }}">
               <div class="cg_inf">
                  <h3>{{ item.shop_name }}</h3>
                  <div class="cg_eva">
                      <ul>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                      </ul>
                      <span>{{ item.shop_score }}</span>
                  </div>
                  <div class="food_sc">
                     <span>起送:￥{{ item.shop_price }}</span><span>配送费:￥{{ item.send_price }}</span><span>时间:{{ item.duration }}分钟</span>
                  </div>
               </div>
            </a>
            </li>
            {% endfor %}
         </ul>
      </div>
   </div>
</div>
<div id="dinner">
   <div class="dinner_title">
      <h2>西餐</h2><a href="{% url 'goods:wm_index' '1' '1'%}">查看全部></a>
   </div>
   <div class="dinner_con_bg">
      <div class="dinner_con">
         <ul>
            {% for item in shop_info1 %}
            <li>
            <a href="{% url 'goods:shop_detail' item.id '1'  '1' '1' %}">
               <img src="{{ item.shop_image }}">
               <div class="cg_inf">
                  <h3>{{ item.shop_name }}</h3>
                  <div class="cg_eva">
                      <ul>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                          <li><img src="{% static 'image/eva.png' %}"></li>
                      </ul>
                      <span>{{ item.shop_score }}</span>
                  </div>
                  <div class="food_sc">
                     <span>起送:￥{{ item.shop_price }}</span><span>配送费:￥{{ item.send_price }}</span><span>时间:{{ item.duration }}分钟</span>
                  </div>
               </div>
            </a>
            </li>
            {% endfor %}
         </ul>
      </div>
   </div>
</div>
<div id="fruit">
   <div class="fruit_title">
      <h2>水果</h2>
   </div>
   <div class="fruit_con">
      <a href="{% url 'goods:wm_index' '2' '1'%}" class="a_href">查看全部></a>
      <div class="fruit_con_ul">
         <ul>
            {% for item in shop_info2 %}
            <li>
               <a href="{% url 'goods:shop_detail' item.id '1' '1' '1' %}"><img src="{{ item.shop_image }}">
                  <div class="sgd_inf">
                      <h3>{{ item.shop_name }}</h3>
                      <div class="cg_eva">
                          <ul>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                          </ul>
                          <span>{{ item.shop_score }}</span>
                      </div>
                      <div class="food_sc">
                         <span>起送:￥{{ item.shop_price }}</span><span>配送费:￥{{ item.send_price }}</span><span>时间:{{ item.duration }}分钟</span>
                      </div>
                  </div>
               </a>
            </li>
            {% endfor %}
         </ul>
      </div>
   </div>
</div>
<div id="drink">
   <div class="drink_title">
      <h2>饮品</h2>
   </div>
   <div class="drink_con">
      <a href="{% url 'goods:wm_index' '3' '1'%}" class="a_href">查看全部></a>
      <div class="drink_con_ul">
         <ul>
            {% for item in shop_info3 %}
            <li>
               <a href="{% url 'goods:shop_detail' item.id '1' '1' '1' %}"><img src="{{ item.shop_image }}">
                  <div class="ypd_inf">
                      <h3>{{ item.shop_name }}</h3>
                      <div class="cg_eva">
                          <ul>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                              <li><img src="{% static 'image/eva.png' %}"></li>
                          </ul>
                          <span>{{ item.shop_score }}</span>
                      </div>
                      <div class="food_sc">
                         <span>起送:￥{{ item.shop_price }}</span><span>配送费:￥{{ item.send_price }}</span><span>时间:{{ item.duration }}分钟</span>
                      </div>
                  </div> 
               </a>
            </li>
            {% endfor %}
         </ul>
      </div>
   </div>
</div>
<div id="service_int">
   <div class="ser_title">
      <h2>服务介绍</h2>
   </div>
   <div class="ser_con">
      <ul>
         <li><a href="{% url 'goods:wm_index' '0' '1' %}"><img src="{% static 'image/ser_1.jpg' %}"><span>中餐</span></a></li>
         <li><a href="{% url 'goods:wm_index' '1' '1'%}"><img src="{% static 'image/ser_2.jpg' %}"><span>西餐</span></a></li>
         <li><a href="{% url 'goods:wm_index' '2' '1'%}"><img src="{% static 'image/ser_3.jpg' %}"><span>水果</span></a></li>
         <li><a href="{% url 'goods:wm_index' '3' '1'%}"><img src="{% static 'image/ser_4.jpg' %}"><span>饮品</span></a></li>
      </ul>
   </div>
</div>
{% endblock body %}

templates/mj.html
<!doctype html>
<html>
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link href="{% static 'css/inc.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div id="top">
        <div class="top1">
          <div class="top1_con">
             <div class="top1_con_f">
                <span>Hi，
                    {% if user.is_authenticated %}
                        <span>{{ user.real_name }}
                        </span>
                    {% endif %}
                </span>
                 <span></span>
             </div>
             <div class="top_lore">
                {% if user.is_authenticated %}
                    <a href="{% url 'user:logout' %}">退出</a>
                    <a href="{% url 'order:query' '1'%}" style="color:#0da2f8;letter-spacing:1px;">订单查询</a>
                {% else %}
				    <a href="{% url 'user:login' %}">请登录</a> <a href="{% url 'user:register' %}">注册</a>
                {% endif %}
             </div>
             <div class="dw_address" style="display: none">
                请选择地址：<input type="text" id="city"  value=""/>
             </div>
             <script type="text/javascript">
                $("#city").click(function (e) {
                    SelCity(this,e);
                    console.log("inout",$(this).val(),new Date())
                });
                </script>
          </div>
       </div>
       <div  class="top2">
          <div class="top2_con">
             <div class="top2_con_f">
                <a href="{% url 'goods:index' %}"><img src="{% static 'image/logo.gif' %}"></a>
             </div>
             <div class="sea_form">
                <form id="searchForm" action="{% url 'goods:haystack' %}" method="get">
                   <input id="q" name="q" type="text" placeholder="搜索商家"><button type="submit">搜索</button>
                </form>
             </div>
             <nav>
                <a href="{% url 'goods:index' %}">首页</a>
                <a href="{% url 'goods:wm_index' '4' '1' %}">外卖</a>
             </nav>
          </div>
       </div>
    </div>
{% endblock header_con %}
<a name="top"> </a>
{# 网站主体内容块 #}
{% block body %}{% endblock body %}
<div style="overflow: hidden;position: fixed;right: 10px;bottom: 20px;z-index: 10;">
    <a href="#top"><img src="{% static 'image/top.png' %}"></a>
</div>
</body>
<footer>
   <div class="foot_nav">
      <a href="{% url 'goods:index' %}">首页</a>|<a href="{% url 'goods:wm_index' '4' '1' %}">外卖</a>|<a href="{% url 'goods:wm_index' '0' '1'%}">中餐</a>|<a href="{% url 'goods:wm_index' '1' '1'%}">西餐</a>|<a href="{% url 'goods:wm_index' '2' '1'%}">水果</a>|<a href="{% url 'goods:wm_index' '3' '1'%}">饮品</a>
   </div>
   <div class="copy_ri">
         <p>吉林省明日科技有限公司Copyright ©2007-2018, All Rights Reserved 吉ICP备10002740号-2 </p>
         <img src="{% static 'image/mrkj.jpg' %}"></div>
   </div>
</footer>
</html>

templates/register.html
<!doctype html>
{#加载静态文件#}
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
<title>吃了么-注册</title>
<link href="{% static 'css/inc.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script language="javascript" type="text/javascript">
    function check() {
        var pwd = $('#pwd').val();
        var cpwd = $('#cpwd').val();
        if (pwd!=cpwd){
            alert('两次密码不一致');
        }
    }
</script>
</head>
<body>
<!--顶部开始-->
<div id="top">
   <div class="top1">
   </div>
   <div class="login_logo">
      <a href="{% url 'goods:index' %}"><img src="{% static 'image/logo.gif' %}"></a>
      <span class="reg_href">已有吃了么账号？<a href="{% url 'user:login' %}">登录</a></span>
   </div>
</div>
<!--顶部结束-->
<!--中间注册-->
<div id="register_main">
{#    此处上传文件需要在form表单添加enctype属性#}
   <form method="post" action="/user/register/" enctype="multipart/form-data" id="register" name="register">
       {% csrf_token %}
      <ul>
         <li><span>账号</span><input type="text" name="user_name" id="user_name"></li>
         <li><span>创建密码</span><input type="password" name="pwd" id="pwd"></li>
         <li><span>确认密码</span><input type="password" name="cpwd" id="cpwd" onchange="check()"></li>
         <li><span>真实姓名</span><input type="text" name="receiver" id="receiver"></li>
         <li><span>联系电话</span><input type="text" name="phone" id="phone"></li>
         <li><span>地址</span><input type="text" name="addr" id="addr"></li>
         <li><span>邮箱</span><input type="text" name="email" id="email"></li>
         <li><span>性别</span><input name="sex" type="radio" value="1"  checked/><span>男</span><input name="sex" type="radio" value="0"/><span>女</span></li>
         <li><span>用户类型</span><input name="mjsj" type="radio" value="0"  checked/><span>买家</span><input name="mjsj" type="radio" value="1"/><span>商家</span></li>
         <li><span>头像</span>
                 <div class="img_yulan">
                    <img id="preview" />
                 </div>
               	<script type="text/javascript">
                    function imgPreview(fileDom){
                        //判断是否支持FileReader
                        if (window.FileReader) {
                            var reader = new FileReader();//创建filereader对象
                        } else {
                            alert("您的设备不支持图片预览功能，如需该功能请升级您的设备！");
                        }
                        //获取文件
                        var file = fileDom.files[0];
                        //读取完成
                        reader.onload = function(e) {
                            //获取图片dom
                            var img = document.getElementById("preview");
                            //图片路径设置为读取的图片
                            img.src = e.target.result;
                        };
                        reader.readAsDataURL(file);
                    }
                </script>
                <input type="file" name="file" onchange="imgPreview(this)">
         </li>
      </ul>
   </form>
   <button class="agree_btn">同意以下协议并注册</button>
    <script language="javascript" type="text/javascript">
        $(".agree_btn").click(function(){
            $("#register").submit();
        });
    </script>
    {{ errmsg }}
</div>
<!--中间注册-->
<footer>
   <div class="foot_nav">
      <a href="index.html">首页</a>|<a href="wm_index.html">外卖</a>|<a href="wm_index.html">中餐</a>|<a href="wm_index.html">西餐</a>|<a href="wm_index.html">水果</a>|<a href="wm_index.html">饮品</a>
   </div>
   <div class="copy_ri">
         <p>吉林省明日科技有限公司Copyright ©2007-2018, All Rights Reserved 吉ICP备10002740号-2 </p>
         <img src=""></div>
   </div>
</footer>
</body>
</html>

templates/sj.html
<!doctype html>
<html>
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link href="{% static 'css/inc.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript">
    window.onload = function () {
        $.ajax({
                url: '/ordermanage/select/',
                data:{'status': status},
                type: 'get',
                dataType: 'json',
                success: function (data) {
                    if (data.res){
                        $("#status").val("start");
                    }else{
                        $("#status").val("stop");
                    }
                }
        })
    }

    function WebSocketTest() {
        var status = $('#status').val();
        if (status == 'start'){
            changestatus(1)
        }else{
            changestatus(0)
            return;
        }
        var num = 0;
        var flag = false;
        var ne = setInterval(function test() {
            $.ajax({
                url: '/ordermanage/new/',
                async: true,
                data:{'shop_id': '1', 'num': num, 'flag': flag},
                type: 'get',
                dataType: 'json',
                success: function (data) {
                    num = data.count;
                    flag = true;
                    if (data.res == 1) {
                        doTTS();
                        alert('您有新订单，请刷新订单页面！');
                        {#window.location.reload();#}
                    }
                    if(!data.status){
                        clearInterval(ne);
                    }
                }
            })
        }, 50000000000000);
    }

    function doTTS() {
        var ttsDiv = document.getElementById('bdtts_div_id');
        var ttsAudio = document.getElementById('tts_autio_id');
        var ttsText = document.getElementById('ttsText').value;
        // 文字转语音
        ttsDiv.removeChild(ttsAudio);
        var au1 = '<audio id="tts_autio_id" autoplay="autoplay">';
        var sss = '<source id="tts_source_id" src="http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&per=3&spd=5&text=' + ttsText + '" type="audio/mpeg">';
        var eee = '<embed id="tts_embed_id" height="0" width="0" src="">';
        var au2 = '</audio>';
        ttsDiv.innerHTML = au1 + sss + eee + au2;
        ttsAudio = document.getElementById('tts_autio_id');
        ttsAudio.play();
    }

    function changestatus(status){
        $.ajax({
                url: '/ordermanage/status/',
                data:{'status': status},
                type: 'get',
                dataType: 'json',
                success: function (data) {
                    alert(data.mes);
                }
        })
    }
    </script>
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div id="sj_top">
       <div class="sj_index_top">
                <a href="{% url 'goods:sj_index' %} "><img src="{% static 'image/logo.gif' %}"></a>
                <select id="status" name="status" onchange="WebSocketTest();">
                   <option value ="start" >营业中</option>
                   <option value ="stop" selected>休息中</option>
                </select>
       </div>
    </div>

    <div style="display: none">
         <input type="text" id="ttsText" value="您有新订单，请刷新订单页面">
         <input type="button" id="tts_btn" onclick="doTTS()" value="播放">
    </div>

    <div id="bdtts_div_id" style="display: none">
         <audio id="tts_autio_id" autoplay="autoplay">
           <source id="tts_source_id" src="http://tts.baidu.com/text2audio?lan=zh&amp;ie=UTF-8&amp;spd=5&amp;per=1&amp;text=" type="audio/mpeg">
           <embed id="tts_embed_id" height="0" width="0" src="">
         </audio>
    </div>
{% endblock header_con %}

{% block main %}
    <div id="main">
        <nav class="sj_nav">
           <ul>
              <li><a href="{% url 'ordermanage:sj_order' '1' %}">订单管理</a></li>
              <li><a href="{% url 'goodsmanage:sj_cpgl' '1' %}">菜品管理</a></li>
              <li><a href="{% url 'commentmanage:mess' '1' '1' '1' %}">留言板管理</a></li>
           </ul>

           <span>注册时间:{{ shop.create_time }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;综合评分：<b>{{ shop.shop_score }}</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'user:logout' %}">退出登录</a></span>
        </nav>
{% endblock main %}
{# 网站主体内容块 #}
{% block body %}{% endblock body %}

{% block endmain %}
    </div>
{% endblock endmain %}
</body>
<footer>
   <div class="foot_nav">
      <a href="{% url 'goods:sj_index' %}">首页</a>|<a href="">外卖</a>|<a href="">中餐</a>|<a href="">西餐</a>|<a href="">水果</a>|<a href="">饮品</a>
   </div>
   <div class="copy_ri">
         <p>吉林省明日科技有限公司Copyright ©2007-2018, All Rights Reserved 吉ICP备10002740号-2 </p>
         <img src="{% static 'image/mrkj.jpg' %}"></div>
   </div>
</footer>
</html>

templates/sj_cpgl.html
{% extends 'sj.html' %}
{% load staticfiles %}
{% block title %}吃了么-菜品管理{% endblock title %}
{% block topfiles %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">
$(function () {
   $('.sj_order_man ul li').hover(function(){
        //获得当前被点击的元素索引值
         var Index = $(this).index();
		 var line=300*Index-300;
		//给菜单添加选择样式
	    $(this).addClass('active').siblings().removeClass('active');
		 $(".line").stop(true,true).animate({left:line},200);
		$('.sj_order_man').children('div').eq(Index).show().siblings('div').hide();
   });
});
</script>
{% endblock topfiles %}
{% block body %}

   <div class="add_cp">
      <h3>添加菜品</h3>
       <form method="post" enctype="multipart/form-data" id="sj_cogl" name="sj_cpgl">
           {% csrf_token %}
          <ul>
             <li><span>商品名称<input type="text" id="name" name="name"></span><span>商品价格<input type="text" id="price" name="price"></span></li>
             <li><span>餐盒价格<input type="text" id="pack" name="pack"></span><span>商品库存<input type="text" id="stock" name="stock"></span></li>
             <li><span>商品类型<input type="text" id="type" name="type"></span></li>
              <li><span>商品图片</span></li>
              <li>
                <div class="img_yulan">
                   <img id="preview" />
                </div>
                <script type="text/javascript">
                  function imgPreview(fileDom){
                      //判断是否支持FileReader
                      if (window.FileReader) {
                          var reader = new FileReader();//创建filereader对象
                      } else {
                          alert("您的设备不支持图片预览功能，如需该功能请升级您的设备！");
                      }
                      //获取文件
                      var file = fileDom.files[0];
                      //读取完成
                      reader.onload = function(e) {
                          //获取图片dom
                          var img = document.getElementById("preview");
                          //图片路径设置为读取的图片
                          img.src = e.target.result;
                      };
                      reader.readAsDataURL(file);
                  }
              </script>
                <input type="file" name="file" onchange="imgPreview(this)">
             </li>
          </ul>
{#           <input type="submit" class="agree_btn" value="点击上架">#}
       </form>
       <button class="agree_btn">点击上架</button>
       <script language="javascript" type="text/javascript">
            $(".agree_btn").click(function(){
                $("#sj_cogl").submit();
            });
        </script>
       {{ errmsg }}
       {{ success }}
       <div class="cp_list">
         <table>
              <tr>
                  <td width="17%">商品名称</td>
                  <td width="7%">商品价格</td>
                  <td width="7%">餐盒价格</td>
                  <td width="7%">库存</td>
                  <td width="15%">商品分类</td>
                  <td width="15%">图片展示</td>
                  <td width="32%">菜品管理</td>
              </tr>
                {% for item in info %}
             <tr>
                 <td>{{ item.name }}</td>
                 <td>{{ item.price }}</td>
                 <td>{{ item.pack }}</td>
                 <td>{{ item.stock }}</td>
                 <td>{{ item.type }}
                 </td>
                 <td>
                    <img src="{{ item.image}}">
                 </td>
                 <td>
                    <button class="cpup_btn"><a href="{% url 'goodsmanage:sj_cpgl_update' item.id %}">点击修改</a></button>
                    <button><a href="{% url 'goodsmanage:update_del' item.id %}" onclick="if(confirm('是否确认删除?')){return true;}else{return false;}">删  除</a></button>
                 </td>
             </tr>
                {% endfor %}

         </table>

         <div class="pagenation">
            {% if info.has_previous %}
				<a href="{% url 'goodsmanage:sj_cpgl' info.previous_page_number %}"> < 上一页</a>
            {% endif %}

            {% for pindex in pages %}
                 {% if pindex == info.number %}
				     <a href="{% url 'goodsmanage:sj_cpgl' pindex %}" class="active">{{ pindex }}</a>
                 {% else %}
				     <a href="{% url 'goodsmanage:sj_cpgl' pindex %}">{{ pindex }}</a>
                 {% endif %}
			{% endfor %}

            {% if info.has_next %}
			    <a href="{% url 'goodsmanage:sj_cpgl' info.next_page_number %}"> 下一页 ></a>
            {% endif %}
		</div>
       </div>
   </div>
{% endblock body %}